[project]
name = "localresearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.5.1",
    "aiohttp>=3.11.15",
    "aiohttp-cors>=0.8.0",
    "einops>=0.8.1",
    "flet>=0.27.6",
    "huggingface-hub[hf-xet]>=0.30.1",
    "mcp[cli]>=1.4.1",
    "pillow>=11.1.0",
    "pymupdf>=1.25.3",
    "pymupdf4llm==0.0.19",
    "rich>=13.9.4",
    "scikit-learn>=1.6.1",
    "sentence-transformers>=3.4.1",
    "torch>=2.6.0",
    "transformers>=4.49.0",
    "umap-learn>=0.5.7",
]

[dependency-groups]
dev = [
    "flet[all]>=0.27.6",
]
